### ISSUE TITLE
missing download_baselines.sh 

### ISSUE THREAD

**Issue by mshanm10** [moonlightlane/QG-Net#1]
Hi,
Script download_baselines.sh  mentioned in the documentation is missing. We are trying to test this. Can you please upload the missing files. 
Thanks, -Muthu

**Comment by zichaow** [comment]
@mshanm10  just added, can you report whether it works? thanks!

**Comment by mshanm10** [comment]
Thanks for adding the file.  we ran the below steps in order.
1. download_baselines.sh downloaded 2 more models.
2. download_preproc_squad.sh  downloaded dev.tar.gz and train.tar.gz
3. skipped preprocessing
4. ran train.sh and got the below error
              Traceback (most recent call last):
               File "OpenNMT-py/train.py", line 357, in <module>
               main()
               File "OpenNMT-py/train.py", line 312, in main
               train_dataset = load_dataset("train")
               File "OpenNMT-py/train.py", line 230, in load_dataset
              dataset = torch.load(opt.data + '.' + data_type + '.pt')
               File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/torch/serialization.py", 
               line 356, in load
                f = open(f, 'rb')
               FileNotFoundError: [Errno 2] No such file or directory: 'data/data.feat.1sent.train.pt'
-----------
1. ran download_raw_squad.sh and got below error
                ./download_raw_squad.sh
                DRQA_DATA not set; downloading to default path ('data').
                ../data/SQuAD-v1.1-train.json: No such file or directory

Thanks

**Comment by moonlightlane** [comment]
@mshanm10  looks like the preprocessed data is missing. I'll get back to you tomorrow re this!

**Comment by zichaow** [comment]
@mshanm10 I forgot a data preparation step that OpenNMT requires. I'll update the `train.sh` file soon but for now can you try run the following command when you are in the `OpenNMT-py` folder before running `train.sh`: `python preprocess.py -train_src ../data/src-train.txt -train_tgt ../data/tgt-train.txt -valid_src ../data/src-val.txt -valid_tgt data/tgt-val.txt -save_data ../data`. You might need to change the paths.

For more info see OpenNMT-py documentation under the section Quickstart: https://github.com/OpenNMT/OpenNMT-py

**Comment by mshanm10** [comment]
we ran the command you mentioned.
1. data folder was missing the files, so, we copied the data folder from original OpenNMT project
2. ran preprocess command in folder /qg-net/OpenNMT-py and got the below error
Command:
python preprocess.py -train_src /qg-net/data/src-train.txt -trc /qg-net/data/src-val.txt -valid_tgt data/tgt-val.txt -save_data /qg-net/data
Error:
Failed to open corpus file: data/tgt-val.txt

**Comment by amitakamath** [comment]
Try `python preprocess.py -train_src /qg-net/data/src-train.txt -train_tgt /qg-net/data/tgt-train.txt -valid_src /qg-net/data/src-val.txt -valid_tgt /qg-net/data/tgt-val.txt -save_data /qg-net/data`

**Comment by zichaow** [comment]
@amitakamath @mshanm10 Hello, sorry for the delays - I've made some updates to the bash scripts and now the preprocessing and downloading should work as expected. Fortunately, none of the glitches are serious; instead, they are just some wrong directories. I've also updated the readme file.

Closing the issue for now; please let me know if you observer further problems. Thanks!
