### ISSUE TITLE
__init__() got an unexpected keyword argument 'tensor_type'

### ISSUE THREAD

**Issue by Erdene-Ochir0417** [moonlightlane/QG-Net#12]
Hello. Thanks for sharing code.

I followed readme but this error occured.

  File "/opt/share-vol/ochiroo/QG-Net/OpenNMT-py/onmt/io/IO.py", line 101, in get_fields
    postprocessing=make_src, sequential=False)
TypeError: __init__() got an unexpected keyword argument 'tensor_type'

How can i fix this?

**Comment by zichaow** [comment]
thanks for trying out the code. this sounds to me like a version problem on top of my head; can you share the versions of the required packages you used? i.e., python version, openNMT version, pytorch version etc.? thanks!

**Comment by zichaow** [comment]
close due to inactivity
