### ISSUE TITLE
python3: symbol lookup error: /usr/local/python3/lib/python3.6/site-packages/torch/lib/libtorch_python.so: undefined symbol: PySlice_Unpack

### ISSUE THREAD

**Issue by 123malin** [moonlightlane/QG-Net#4]
我用的环境是python3.6，执行./qg_reproduce_LS.sh时报错
`[root@VM_0_8_centos test]# ./qg_reproduce_LS.sh
Loading model parameters.
  0%|                                                                                                                                                                                | 0/11 [00:00<?, ?it/s]/usr/local/python3/lib/python3.6/site-packages/torchtext/data/field.py:197: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  return Variable(arr, volatile=not train), lengths
/usr/local/python3/lib/python3.6/site-packages/torchtext/data/field.py:198: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  return Variable(arr, volatile=not train)
python3: symbol lookup error: /usr/local/python3/lib/python3.6/site-packages/torch/lib/libtorch_python.so: undefined symbol: PySlice_Unpack
[root@VM_0_8_centos test]#`

**Comment by zichaow** [comment]
看起来是pytorch版本的问题；后面的版本好像移除了volatile。你的pytorch版本是多少？我用的是pytorch 0.4.1。你把pytorch降到0.4.1试试？

**Comment by zichaow** [comment]
closed due to inactivity
