### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by shizhediao** [moonlightlane/QG-Net#5]
Hi, when I'm downloading the prepro_squad, I encountered with these questions. Could help me? Thanks

--2019-01-29 11:42:32--  https://rice.box.com/shared/static/6haddoiep15fmdqmtdp3ccf44o1m6e4z.gz
Resolving rice.box.com... 107.152.24.197
Connecting to rice.box.com|107.152.24.197|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://rice.app.box.com/shared/static/6haddoiep15fmdqmtdp3ccf44o1m6e4z.gz [following]
--2019-01-29 11:42:34--  https://rice.app.box.com/shared/static/6haddoiep15fmdqmtdp3ccf44o1m6e4z.gz
Resolving rice.app.box.com... 8.7.198.45
Connecting to rice.app.box.com|8.7.198.45|:443... failed: Connection refused.
preprocessed data download completed.

**Comment by zichaow** [comment]
Sorry to hear about the connection issues. Does it work if you click on the link and manually download? If not I can share it with you directly thanks!

**Comment by shizhediao** [comment]
> Sorry to hear about the connection issues. Does it work if you click on the link and manually download? If not I can share it with you directly thanks!

Thanks very much! I managed to download the dataset now.
Thanks!
