### ISSUE TITLE
Could you share the baseline code?

### ISSUE THREAD

**Issue by shizhediao** [moonlightlane/QG-Net#7]
Hi, I noticed that you shared the checkpoint of two baseline.
Could you share the baseline code? because I'd like to reproduce the result for baseline with my own dataset, thanks !

**Comment by zichaow** [comment]
Hi, again sorry for very late reply... if you are referring to the NN-based baseline, then it is just a different setting of the code provided (e.g., remove the answer information). The other, non-NN based baseline is not publicly available; I obtained it from the authors of a different paper. Hope this still helps!
